remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
text-col: "#000000"
title: <h4 style="color:#a8d3a0;">Ellen Løvhaug Harrison</h4>
description: <b>Ellen Løvhaug Harrison</b> (f. 1994) er utdanna ved Skrivekunstakademiet og har studert litteraturvitskap i Bergen. Ho bur og arbeider i Oslo.
